name: Daily Script

on:
  schedule:
    - cron: '25 1 * * *'  # Every day at 01:25 UTC

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt || true

      - name: Run script
        run: python ./scripts/script.py
