name: Daily Script

env:
  GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}

permissions:
  contents: write  # Allow the workflow to push changes to the repository


on:
  workflow_dispatch:
  schedule:
    - cron: '25 1 * * *'  # Every day at 01:25 UTC

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt || true

      - name: Run script
        run: python ./scripts/scrape.py

      # - name: Run gem script
        # run: python ./scripts/gem.py

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          if ! git diff --cached --quiet; then
            git commit -m "Daily script updates"
            git push
          else
            echo "No changes to commit"
          fi
